obstacle_range: 1.7
raytrace_range: 3.0
footprint: [[0.225, 0.13], [0.225, -0.13], [-0.225, -0.13], [-0.225, 0.13]]
footprint_inflation: 0.2
robot_radius: 0.175
inflation_radius: 0.1
max_obstacle_height: 0.8
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: scan, marking: true, clearing: true, expected_update_rate: 0}

static_layer:
  enabled:  true
  map_topic: "/map"
