controller_frequency: 10.0   # freq of update trace planning
recovery_behavior_enabled: true
clearing_rotation_allowed: false

DWAPlannerROS:
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_th: 0.1
  max_trans_vel: 0.55
  min_trans_vel: 0.2
  max_vel_x: 0.255
  min_vel_x: -0.1
  max_vel_y: 0
  min_vel_y: 0
  max_rot_vel: 0.25
  min_rot_vel: 0.4

  yaw_goal_tolerance: 0.17
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: true

  sim_time: 1.5
  sim_granularity: 0.025
  vx_samples: 8
  vy_samples: 0
  vtheta_samples: 20
  penalize_negative_x: true

  path_distance_bias: 10
  goal_distance_bias: 0.8
  occdist_scale: 0.01
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  oscillation_reset_dist: 0.05

  prune_plan: true  
  sim_period: 0.1
  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01

  publish_cost_grid_pc: true
  cheat_factor: 2
